name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: hubui

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Run linting
      run: bun run lint

    - name: Check build
      run: bun run build

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Validate Dockerfile
      run: |
        docker run --rm -i hadolint/hadolint < Dockerfile || echo "Dockerfile linting completed with warnings"

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
        labels: |
          org.opencontainers.image.title=HubUI
          org.opencontainers.image.description=Modern web application built with Next.js, React, and TypeScript
          org.opencontainers.image.vendor=HubUI
          org.opencontainers.image.licenses=MIT

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      id: build
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Run Trivy vulnerability scanner
      if: github.event_name != 'pull_request'
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      if: github.event_name != 'pull_request'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Generate deployment files
      if: github.event_name != 'pull_request'
      run: |
        mkdir -p deployment
        
        # Create docker-compose.yml for easy deployment
        cat > deployment/docker-compose.yml << 'EOF'
        services:
          hubui:
            image: ${{ secrets.DOCKER_USERNAME }}/hubui:latest
            ports:
              - "3000:3000"
            environment:
              - NODE_ENV=production
              - PORT=3000
              - HOSTNAME=0.0.0.0
            restart: unless-stopped
            healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:3000/api/health", "||", "curl", "-f", "http://localhost:3000/"]
              interval: 30s
              timeout: 10s
              retries: 3
              start_period: 40s
            networks:
              - hubui-network
            deploy:
              resources:
                limits:
                  memory: 512M
                  cpus: '0.5'
                reservations:
                  memory: 256M
                  cpus: '0.25'
        
        networks:
          hubui-network:
            driver: bridge
        EOF
        
        # Create deployment README
        cat > deployment/README.md << 'EOF'
        # HubUI Deployment
        
        ## Quick Start with Docker Compose
        
        1. Download the docker-compose.yml file
        2. Run the application:
        
        ```bash
        docker compose up -d
        ```
        
        The application will be available at http://localhost:3000
        
        ## Quick Start with Docker Run
        
        ```bash
        docker run -d \
          --name hubui \
          -p 3000:3000 \
          -e NODE_ENV=production \
          --restart unless-stopped \
          --memory="512m" \
          --cpus="0.5" \
          ${{ secrets.DOCKER_USERNAME }}/hubui:latest
        ```
        
        ## Environment Variables
        
        - `NODE_ENV`: Set to 'production' for production deployment
        - `PORT`: Port to run the application on (default: 3000)
        - `HOSTNAME`: Hostname to bind to (default: 0.0.0.0)
        
        ## Health Check
        
        The container includes a health check that monitors the application status.
        You can check the health status with:
        
        ```bash
        docker ps
        ```
        
        ## Resource Limits
        
        The default configuration sets resource limits:
        - Memory: 512MB limit, 256MB reserved
        - CPU: 0.5 cores limit, 0.25 cores reserved
        
        ## Stopping the Application
        
        ### Docker Compose
        ```bash
        docker compose down
        ```
        
        ### Docker Run
        ```bash
        docker stop hubui
        docker rm hubui
        ```
        
        ## Security Notes
        
        - The application runs as a non-root user (nextjs:nodejs)
        - Regular security scans are performed on the Docker image
        - Health checks ensure the application is running properly
        EOF

    - name: Upload deployment artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: deployment-files
        path: deployment/
        retention-days: 30

    - name: Update Docker Hub description
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/hubui
        short-description: "HubUI - Modern web application built with Next.js, React, and TypeScript"
        readme-filepath: ./README.md

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: deployment/*
        generate_release_notes: true
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
